declare const styles: {
  readonly container: string;
  readonly loading: string;
  readonly loadingSpinner: string;
  readonly spinner: string;
  readonly loadingText: string;
  readonly empty: string;
  readonly emptyIcon: string;
  readonly emptyTitle: string;
  readonly emptyDescription: string;
  readonly header: string;
  readonly resultCount: string;
  readonly results: string;
  readonly result: string;
  readonly resultHeader: string;
  readonly resultTitle: string;
  readonly resultMeta: string;
  readonly category: string;
  readonly difficulty: string;
  readonly difficultyBeginner: string;
  readonly difficultyIntermediate: string;
  readonly difficultyAdvanced: string;
  readonly difficultyExpert: string;
  readonly excerpt: string;
  readonly highlights: string;
  readonly highlightItem: string;
  readonly highlight: string;
  readonly tags: string;
  readonly tag: string;
  readonly resultFooter: string;
  readonly slug: string;
  readonly relevance: string;
};

export default styles;
